services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_PATH: ""
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      PORT: 3000
    restart: unless-stopped
    ports:
      - "3000:3000"
